Article
arnaudpant/vinted pull request #10
Opened 2024-01-11 12:17 UTC by BaptisteGrimaldi

config fait , style fait , composant presque fait je vais picker le code d'arnautl pour le terminer

2024-01-13 19:24 UTC, ghorreso commented on src/pages/Home.tsx
> +  const [usersFilActu, setUsersFilActu] = useState<User[]>([]);
Les variables ont un mix de français et anglais. Cela serait donc plutôt : 

```tsx

  const [productsCreator, setProductsCreator] = useState<Product[]>([]);
  const [productsPopular, setProductsPopular] = useState<Product[]>([]);

  const [productsNewsFeed, setProductsNewsFeed] = useState<Product[]>([]);
  const [usersNewsFeed, setUsersNewsFeed] = useState<User[]>([]);
```

2024-01-13 19:27 UTC, ghorreso commented on src/pages/Home.tsx
> +        const data = await response.json() as Product[];
`data` est le résultat d'un `await` donc c'est un `Promise<Product[]>`

2024-01-13 19:27 UTC, ghorreso commented on src/pages/Home.tsx
> +        const usersData = await response.json() as User[];
`usersData` est le résultat d'un `await` donc c'est un `Promise<User[]>`

2024-01-13 19:31 UTC, ghorreso commented on src/pages/Home.tsx
> +        const response = await fetch('https://fakestoreapi.com/products');
`'https://fakestoreapi.com'` doit être stocké dans une variable d'environnement dans .env et donc mettre à jour .env.exemple pour gérer un changement d'url d'api.

2024-01-13 19:32 UTC, ghorreso commented on src/pages/Home.tsx
> +        console.error('Erreur lors de la récupération des données :', error);
Le message d'erreur doit être en anglais

2024-01-13 19:33 UTC, ghorreso commented on src/pages/Home.tsx
> +  const marques: string[] = [
`marques` c'est du français donc ça doit être `brands`

2024-01-13 19:45 UTC, ghorreso requested changes
Quelques petits changements à faire

2024-01-13 19:45 UTC, ghorreso commented on src/types/types.ts
> +//C'est normal que j'ai désactivé eslint ici les type sont  partagé dans tout le projet a chaque que vous typer
Je n'ai pas compris cette phrase, surtout la fin "ici les type sont  partagé dans tout le projet a chaque que vous typer"

2024-01-13 19:45 UTC, ghorreso commented on src/components/home/FilActu.tsx
> +const FilActu = ({
Changer le nom en anglais donc `NewsFeed`

2024-01-13 19:45 UTC, ghorreso commented on src/components/home/FilActu.tsx
> +            key={index}
Tu peux utiliser `product.id` pour la clé du map

2024-01-13 19:45 UTC, ghorreso commented on tailwind.config.ts
> +      '.toutVoir': {
Faut le changer en `'.seeAll'`

2024-01-13 22:18 UTC, BaptisteGrimaldi commented on src/types/types.ts
> +//C'est normal que j'ai désactivé eslint ici les type sont  partagé dans tout le projet a chaque que vous typer
en gros en temps normal on est obliger d'importer les types de ts sur un composant mais dans ce projet on en à pas besoin on peux juste mettre les type dans le fichiers types et ils sont partager dans tous le projet , le problème c'est que eslint aime pas l'export des types pour une raison que j'ignore en vrai y pas d'erreurs mais sa met qu'il y en a une alors que non ducoup faut juste désactiver eslint dans ce fichier , je vais donc le faire et enlever les commentaire ce sera plus simple pour tous le monde

2024-01-13 22:23 UTC, BaptisteGrimaldi commented on src/pages/Home.tsx
> +  const [usersFilActu, setUsersFilActu] = useState<User[]>([]);
fait

2024-01-13 22:26 UTC, BaptisteGrimaldi commented
modif faite en attente du 2nd check

2024-01-14 00:39 UTC, ghorreso commented on src/types/types.ts
> +//C'est normal que j'ai désactivé eslint ici les type sont  partagé dans tout le projet a chaque que vous typer
Pourquoi on n'a pas besoin d'importer les types dans ce projet ?

2024-01-14 01:13 UTC, ghorreso requested changes
La gestion de types.ts à clarifier, et il ne faut pas merger cet PR car ça a été ouvert sur master

2024-01-14 21:34 UTC, BaptisteGrimaldi commented on src/types/types.ts
> +//C'est normal que j'ai désactivé eslint ici les type sont  partagé dans tout le projet a chaque que vous typer
heu de mon coté y a aucun problème... : 
![image](https://github.com/arnaudpant/vinted/assets/100611587/08e9a365-c256-45ef-b33a-6e69924c0925)

2024-01-14 21:36 UTC, BaptisteGrimaldi commented
"La gestion de types.ts à clarifier, et il ne faut pas merger cet PR car ça a été ouvert sur master" donc j'en refais une autre depuis develop ?

2024-01-14 22:03 UTC, closed without merging