Feature/header banner
arnaudpant/vinted pull request #12
Opened 2024-01-13 18:26 UTC by belewen

Sprint 1 :
Suite au premier Pull Requel

2024-01-13 18:55 UTC, ghorreso commented on src/components/header/navigationBar/Categories.tsx
> +  const isNavBarClicked = (): void => {
Il manque le useCallback sur isNavBarClicked

2024-01-13 18:56 UTC, ghorreso commented on src/data/categoriesHeader.ts
Export default à utiliser
Uniformiser le nom de l'objet `headerCategories` et le nom du fichier `categoriesHeader`

2024-01-13 18:58 UTC, ghorreso commented on src/components/header/navigationBar/SubCategories.tsx
> +        ) : null}
La ternaire n'est pas nécessaire vu que avec &&, si `activeSubCategory?.subSubCategories` est undefined, ça renvoie null

```tsx
        {activeSubCategory?.subSubCategories && (
          <SubSubCategories
            subSubCategories={activeSubCategory.subSubCategories}
          />
        )}
```

2024-01-13 18:59 UTC, ghorreso commented on src/components/header/TopHeader.tsx
> +export const TopHeader: () => JSX.Element = () => {
Tu utilises encore un `export const` au lieu d'un default

2024-01-13 19:02 UTC, ghorreso requested changes
Quelques changements encore nécessaires

2024-01-14 14:09 UTC, belewen commented on src/components/header/navigationBar/Categories.tsx
> +  const isNavBarClicked = (): void => {
Nouveau code 

```
const isNavBarClicked = useCallback((): void => {
    document.addEventListener('click', (event) => {
      const elementClicked = (event.target as Node) || null;
      if (!elementClicked) {
        return;
      }
      if (!divCategorieRef?.current?.contains(elementClicked)) {
        setDisplayOnScreenPopCategories(false);
      } else {
        setDisplayOnScreenPopCategories(true);
      }
    });
  }, [setDisplayOnScreenPopCategories]);
```

2024-01-14 14:12 UTC, belewen commented on src/data/categoriesHeader.ts
Corrigé

2024-01-14 14:13 UTC, belewen commented on src/components/header/navigationBar/SubCategories.tsx
> +        ) : null}
Corrigé

2024-01-14 14:14 UTC, belewen commented on src/components/header/TopHeader.tsx
> +export const TopHeader: () => JSX.Element = () => {
Corrigé

2024-01-14 16:57 UTC, ghorreso approved these changes
C'est maintenant pour être mergé

2024-01-14 17:45 UTC, merged