Feat/crud firebase
arnaudpant/vinted pull request #16
Opened 2024-01-16 20:49 UTC by arnaudpant

=== SPRINT 2 ===
2 Features a valider: 
- Box-info-vendeur
- CRUD Firebase

2024-01-22 18:38 UTC, belewen requested changes
review finie

2024-01-22 18:38 UTC, nabilCodeur commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +    const randomNumber = Math.floor(Math.random() * 8);
A quoi correspond le 8 ?
A quoi correspond randomNumber ? C'est un index aléatoire du tableau ?

2024-01-22 18:38 UTC, nabilCodeur commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +                  />
Je pense qu'il serait plus proche de la réalité de créer un code du type:
const randomNoteUser = Math.ceil(....  //  randomUser un nombre entrier entre 1 et 5.
Puis de générer le nombre de Star en conséquence

2024-01-22 18:38 UTC, nabilCodeur commented on src/components/suggestion/SuggestionSearch.tsx
> +import { ListSuggestSearchFromVinted } from '../../api/api';
A quoi sert ce composant SuggestionSearch? 
Je ne le vois utilisé nulle part dans le projet

2024-01-22 18:38 UTC, nabilCodeur commented on src/components/suggestion/CardSuggestionSearch.tsx
> +const CardSuggestionSearch = ({ product }: Props) => {
Ce composant est utilisé par SuggestionSearch. SuggestionSearch n'est pas utilisé ailleurs dans le projet

2024-01-22 18:38 UTC, nabilCodeur commented on src/components/ui/ChevronPosition.tsx
> +  return <></>;
Mettre à la place
`return null`

2024-01-22 18:38 UTC, nabilCodeur commented on src/firebase/firestore.ts
> +export const FirestoreUpdateDocument = async (collectionName: string, documentId: string, data: object) => {
Le type de retour de la fonction n'est pas explicité.
Est-il possible de détailler data:object ?

2024-01-22 18:38 UTC, nabilCodeur commented on src/hooks/useAddArticle.ts
> +    const addNewArticleInFirestore = async (newListArticlesToSell: ArticleForSale[]) => {
addNewArticleInFirestore n'est pas retourné par le custum hook.

2024-01-22 18:38 UTC, nabilCodeur commented on src/hooks/useDataFakeShop.ts
> +const useDataFakeShop = () => {
Créer une fonction qui fetch la data puis qui sera réutiliser par les  fonctions getCategoriesFakeShop, getProductsFakeShop etc...

2024-01-22 18:38 UTC, nabilCodeur commented on src/components/ui/ChevronPosition.tsx
> +import { ChevronRight, ChevronLeft } from 'lucide-react';
Utilsié seulement par SuggestionSearch. SuggestionSearch n'est pas utilisé ailleurs

2024-01-22 18:38 UTC, nabilCodeur commented on src/hooks/useAddArticle.ts
> +    const addArticleToSell = (article: ArticleForSale) => {
Quels sont les différences de rôles entre addNewArticleInFirestore ET addArticleToSell ?

2024-01-22 18:38 UTC, nabilCodeur commented on src/hooks/useAddArticle.ts
> +            console.log('addArticleToSell', newListArticlesToSell)
Eviter les console.log pour la branche develop

2024-01-22 18:38 UTC, nabilCodeur commented on src/hooks/useAddArticle.ts
> +                console.error(error.message, { autoClose: 3000 });
remplacer par throw Error qui sera capturé plus tard par un ErrorBoundary

2024-01-22 18:38 UTC, belewen commented on src/pages/NewArticle.tsx
> +        {/* FORMULAIRE */}
Ce fichier est très long. Le découper en AddProductPhoto , AddProductDescription et AddProductPrice faciliterait la lecture.

2024-01-22 18:38 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +describe('Affichage de M ou K', () => {
Remplacer par "Doit afficher M ou K pour le nombre de vues"

2024-01-22 18:38 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +test('Tests si affichage du bon titre', () => {
Remplacer par "Le titre de CardSuggestionSearch doit être 'Marque du produit' "

2024-01-22 18:38 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +  test('Tests si affichage du K', () => {
Spécifier que c'est pour le nombre de vues de CardSuggestionSearch

2024-01-22 18:38 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +  test('Tests si affichage du M', () => {
Spécifier que c'est pour le nombre de vues de CardSuggestionSearch

2024-01-22 22:40 UTC, arnaudpant commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +    const randomNumber = Math.floor(Math.random() * 8);
C'est pour avoir un numéro aleatoire entre 1 & 7 en sachant que le 8eme l'avatar ne s'affiche pas

2024-01-22 22:41 UTC, arnaudpant commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +                  />
C'est ce que je voulais faire mais apres plusieurs tests ca ne fonctionnait pas donc j'ai laissé comme ca

2024-01-22 22:41 UTC, arnaudpant commented on src/components/suggestion/SuggestionSearch.tsx
> +import { ListSuggestSearchFromVinted } from '../../api/api';
Le PR aurait du etre en draft, ca c'est pour la partie CRUD que j'ai pas fini

2024-01-22 22:42 UTC, arnaudpant commented on src/components/suggestion/CardSuggestionSearch.tsx
> +const CardSuggestionSearch = ({ product }: Props) => {
idem pas terminé

2024-01-23 13:59 UTC, belewen commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +    const randomNumber = Math.floor(Math.random() * 8);
Il faudrait faire const LAST_USER_ID = 7

2024-01-23 14:03 UTC, belewen commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +                  />
Pour mon sprint 3 avec la fiche user, j'ai été confronté à la même problématique. 
Ce code a fonctionné. 

```
{Array.from({ length: fakeStarsUser }, (_, index) => (
              <Star fill={'orange'} strokeWidth={0} key={index} />
            ))}
```

2024-01-23 21:21 UTC, arnaudpant commented on src/components/ui/ChevronPosition.tsx
> +  return <></>;
corrigé

2024-01-23 21:24 UTC, arnaudpant commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +                  />
j'ai remplacé par ton code

2024-01-23 21:25 UTC, arnaudpant commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +    const randomNumber = Math.floor(Math.random() * 8);
corrigé

2024-01-23 21:29 UTC, arnaudpant commented on src/components/suggestion/SuggestionSearch.tsx
> +import { ListSuggestSearchFromVinted } from '../../api/api';
C'est une liste de suggestion codée en dur qui permet d'afficher 10 suggestions, je suppose que Vinted affiche les requettes le plus demandées par les utilisateurs mais nous on n'a pas ces infos. C'est pour cela que j'ai codé ca en dur

2024-01-23 21:31 UTC, arnaudpant commented on src/components/suggestion/CardSuggestionSearch.tsx
> +const CardSuggestionSearch = ({ product }: Props) => {
c'est pour faire la meme "combine" que Vinted et ne pas avoir la barre de scroll horizontale qui apparait

2024-01-23 21:35 UTC, arnaudpant commented on src/pages/NewArticle.tsx
> +        {/* FORMULAIRE */}
je voulais le découper mais j'utilise react-hook-form et c'est un formulaire pour la grande partie du code. Le découper entraine une multitude de pb et des props a ne plus en finir. J'ai juste mis la logique d'envoi des datas dans un autre composant pour alleger la vue mais pour le formulaire beaucoup plus simple et rapide de le laisser dans un seul composant

2024-01-23 21:36 UTC, arnaudpant commented on __tests__/CardSuggestionSearch.test.tsx
> +describe('Affichage de M ou K', () => {
Corrigé

2024-01-23 21:36 UTC, arnaudpant commented on __tests__/CardSuggestionSearch.test.tsx
> +test('Tests si affichage du bon titre', () => {
corrigé

2024-01-23 21:37 UTC, arnaudpant commented on __tests__/CardSuggestionSearch.test.tsx
> +  test('Tests si affichage du K', () => {
redondant par rapport au-dessus

2024-01-23 21:38 UTC, arnaudpant commented on __tests__/CardSuggestionSearch.test.tsx
> +  test('Tests si affichage du M', () => {
corrigé

2024-01-26 19:42 UTC, belewen commented on src/components/suggestion/SuggestionSearch.tsx
> +import { ListSuggestSearchFromVinted } from '../../api/api';
ok

2024-01-26 19:42 UTC, belewen commented on src/components/suggestion/CardSuggestionSearch.tsx
> +const CardSuggestionSearch = ({ product }: Props) => {
ok

2024-01-26 19:43 UTC, belewen commented on src/pages/NewArticle.tsx
> +        {/* FORMULAIRE */}
ok gardons ce code dans ce cas

2024-01-27 10:07 UTC, arnaudpant commented on src/hooks/useAddArticle.ts
> +    const addNewArticleInFirestore = async (newListArticlesToSell: ArticleForSale[]) => {
Normal c'est une function interne qui ne sert qu'ici

2024-01-27 10:10 UTC, arnaudpant commented on src/hooks/useAddArticle.ts
> +            console.log('addArticleToSell', newListArticlesToSell)
yes c'etait pour le développement, effacé

2024-01-27 10:11 UTC, arnaudpant commented on src/hooks/useAddArticle.ts
> +                console.error(error.message, { autoClose: 3000 });
Oui et ... non ! 
Tant que ErrorBoundary n'est pas implémenté je pense qu'il vaut mieux laissé comme ca.

2024-01-27 10:13 UTC, arnaudpant commented on src/hooks/useAddArticle.ts
> +    const addArticleToSell = (article: ArticleForSale) => {
addNewArticleInFirestore est appelée par addArticleToSell, ce qui permet de séparer la logique entre:
- Je récupère les data du formulaire
- Je les envoie dans Firestore

2024-01-27 10:14 UTC, arnaudpant commented on src/components/ui/ChevronPosition.tsx
> +import { ChevronRight, ChevronLeft } from 'lucide-react';
Pas compris ce que tu veux dire

2024-01-27 16:07 UTC, arnaudpant commented on src/hooks/useDataFakeShop.ts
> +const useDataFakeShop = () => {
Fait

2024-01-27 16:09 UTC, arnaudpant commented on src/firebase/firestore.ts
> +export const FirestoreUpdateDocument = async (collectionName: string, documentId: string, data: object) => {
oula, compliqué avec firebase ... c'est une function a eux, trop long a creuser

2024-01-30 17:02 UTC, belewen commented on src/hooks/useAddArticle.ts
> +    const addNewArticleInFirestore = async (newListArticlesToSell: ArticleForSale[]) => {
ok

2024-01-30 17:03 UTC, nabilCodeur commented on src/firebase/firestore.ts
> +export const FirestoreUpdateDocument = async (collectionName: string, documentId: string, data: object) => {
ok on laisse comme ça

2024-01-30 17:03 UTC, belewen commented on src/components/box-infos-vendeur/BoxInfosVendeur.tsx
> +                  />
ok

2024-01-30 17:09 UTC, belewen commented on src/components/ui/ChevronPosition.tsx
> +import { ChevronRight, ChevronLeft } from 'lucide-react';
Je voulais dire que ChevronPosition.tsx est utilisé uniquement par SuggestionSearch.tsx
Puis SuggestionSearch n'est pas utilisé ailleurs dans le projet

La remaque est caduque vu tes réponses précédentes.

2024-01-30 17:17 UTC, belewen commented on src/hooks/useAddArticle.ts
> +    const addArticleToSell = (article: ArticleForSale) => {
ok, je pense qu'ajouter un commentaire sur ce que fait chaque fonction serait utile

2024-01-30 17:17 UTC, belewen commented on src/hooks/useAddArticle.ts
> +            console.log('addArticleToSell', newListArticlesToSell)
ok

2024-01-30 17:17 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +describe('Affichage de M ou K', () => {
ok

2024-01-30 17:18 UTC, nabilCodeur commented on __tests__/CardSuggestionSearch.test.tsx
> +test('Tests si affichage du bon titre', () => {
ok

2024-01-30 17:18 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +  test('Tests si affichage du K', () => {
ok

2024-01-30 17:18 UTC, belewen commented on __tests__/CardSuggestionSearch.test.tsx
> +  test('Tests si affichage du M', () => {
ok

2024-01-31 12:44 UTC, arnaudpant commented on src/hooks/useAddArticle.ts
> +    const addArticleToSell = (article: ArticleForSale) => {
fait

2024-01-31 14:51 UTC, belewen approved these changes

2024-01-31 21:11 UTC, merged