feat: article infos (Sprint 2)
arnaudpant/vinted pull request #17
Opened 2024-01-20 20:05 UTC by ghorreso

=== SPRINT 2 ===

Feature infos d'un article 
- J'ai implémenté les éléments que j'ai considérés essentiels pour cette feature. Je n'ai pas codé les éléments qui n'apportent pas vraiment de nouvelles fonctionnalités comme les modals où des infos supplémentaires "Tableau des tailles de montre" ou le modal des infos "Protection acheteurs".
- Dans un prochain sprint, il faudra implémenter ce qui se passe quand on clique sur "Acheter" => tâche Trello [Page /checkout?transaction_id=xxx](https://trello.com/c/1SZRsY4a/57-page-checkouttransactionidxxx)
- Dans un prochain sprint, il faudra implémenter ce qui se passe quand on clique sur "Favoris" => tâche Trello [Page ajout d'un article favori et liste des favoris](https://trello.com/c/EA48cgFB/58-page-ajout-dun-article-favori-et-liste-des-favoris)
- J'ai utilisé un src\data\testProduct.ts, en attendant que le contexte d'Arnaud pour récupérer les produits soit dispo dans develop

2024-01-21 20:14 UTC, belewen commented on src/pages/Article.tsx
> +    return <></>;
Envisager un throw Error, qui sera capturé plus tard dans un ErrorBoundary.
Retourner null à la place de <></>

2024-01-21 20:20 UTC, belewen commented on src/components/ArticleInfo.tsx
> +  );
La div globale étant vide, un fragment serait plus judicieux. 
Pour le h2 , font-medium n'existe pas avec tailwind. https://tailwindcss.com/docs/font-size

2024-01-21 20:26 UTC, belewen commented on src/components/articleInfo/ArticlePrices.tsx
> +          price={price}
![image](https://github.com/arnaudpant/vinted/assets/87059307/f559302b-61c2-4137-82ec-ab356bbe4128)
Lorsque je clique sur 72.08€ acheteurs inclus, aucune modal ne s'affiche à l'écran

2024-01-21 21:49 UTC, ghorreso commented on src/components/articleInfo/ArticlePrices.tsx
> +          price={price}
Comme discuté dans Discord, faut désactiver des lignes dans App.tsx pour pouvoir cliquer sur les liens. Le App.tsx ressemble alors à ça

```tsx
function App() {
  return (
    <div className="flex flex-col">
      {/* <Header />
      <div className="relative z-[-10] mt-24"> */}
      <BrowserRouter>
        <Routes>
          <Route path="/" element={<Home />} />
          {/* Page Achat */}
          <Route path="/item/:id" element={<Article />} />
          {/* Page vente si connecté */}
          <Route path="/new" element={<NewArticle />} />
          {/* Page de recherche global */}
          <Route path="/search" element={<Search />} />
          {/* Page de recherche par categorie via navbar */}
          <Route path="/catalog/:id" element={<Catalog />} />
          <Route path="/*" element={<Error404 />} />
        </Routes>
      </BrowserRouter>
      {/* </div> */}
    </div>
  );
}
```

2024-01-21 21:58 UTC, ghorreso commented
Modifs ajoutés suites aux commentaires

2024-01-22 14:49 UTC, belewen requested changes
Je n'ai pas de commentaires supplémentaires à ajouter

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
Un tableau html serait plus adapté

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/ArticleDetails.tsx
> +    <div className="grid grid-cols-2 text-vintedTextGrisFonce">
Attention au rendu sur ordinateur. J'obtiens ce résultat

![image](https://github.com/arnaudpant/vinted/assets/87059307/9f10a025-b0fb-46f8-a0a0-d5ad117d71b1)

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/ArticleInfo.tsx
> +        <span>{description}</span>
Externaliser dans un autre composant ArticleDescription pour facilier la lecture

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +    <div className="flex flex-row justify-between my-4">
Le code peut  être simplifié

```
 <div className="flex flex-row justify-between my-4"> // Puis modifier la flex en fonction du rendu
      <p>Envoi <span className="text-vintedTextGrisFonce">
        à partir de {shippingFee}&nbsp;€
      </span></p>
      
    </div>
```

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/ArticleInfoButtons.tsx
> +    </div>
Eviter la duplication de code. 
Créer un composant ButtonArticle  puis par exemple
`<ButtonArticle backound = "bg-vintedGreen" textColor = "text-white">Acheter</ButtonArticle>`

Attention au rendu sur ordinateur


![image](https://github.com/arnaudpant/vinted/assets/87059307/6d61512f-b2ec-45cf-bcf0-98a7db73e656)

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/BuyerProtectionInfo.tsx
> +        </svg>
Le svg devrait être externaliser dans les assets

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/BuyerProtectionInfo.tsx
> +    </div>
Utiliser plutôt un paragraphe au lieu de span

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/ArticlePrices.tsx
> +  const [modalPriceDetails, setModalPriceDetails] = useState<boolean>(false);
Est ce utile de créer un type qui ne servira qu'ici et qui ne contient qu'un number ?

Je mettrais plutôt

const ArticlesPrices : React.FC<{price:number}> = ({price})...

2024-01-22 14:49 UTC, nabilCodeur commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +};
La création de ce type est-elle pertinente?

const ArticleShippingInfo : React.FC<{price:number}> = ({price})...

2024-01-22 14:49 UTC, nabilCodeur commented on __tests__/ArticleInfo.test.tsx
> +const testProduct: FakeProduct = {
Externaliser dans un fichier ce testProduct, qui peut être utile pour d'autres tests. Dans le fichier const.ts

2024-01-22 14:49 UTC, belewen commented on src/components/ArticleInfo.tsx
> +};
Le type de article peut être défini directement dans ArticleInfo

2024-01-25 21:44 UTC, ghorreso commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
Pourquoi un tableau serait plus adapté ?

2024-01-25 21:44 UTC, ghorreso commented on src/components/articleInfo/ArticleDetails.tsx
> +    <div className="grid grid-cols-2 text-vintedTextGrisFonce">
Oui c'est normal vu qu'il n'y a pas les autres éléments de la page.

2024-01-25 21:46 UTC, ghorreso commented on src/components/ArticleInfo.tsx
> +        <span>{description}</span>
Je ne vois pas trop l'intérêt pour une seule ligne.

2024-01-25 21:49 UTC, ghorreso commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +    <div className="flex flex-row justify-between my-4">
"Envoi" et "à partir de" doivent être dans 2 éléments html différents pour que la flexbox fasse le boulot.

Et je ne comprends pas ce que tu veux dire par "modifier la flex en fonction du rendu"

2024-01-25 21:58 UTC, ghorreso commented on src/components/articleInfo/ArticleInfoButtons.tsx
> +    </div>
Ok donc un composant ArticleButton est utilisé pour les 3 premiers boutons. Le dernier est différent donc je l'ai laissé tel quel.

Pour le rendu sur ordi, pareil que les commentaires précédents, je ne sais pas ce que tu attends en plus vu que les autres éléments ne sont pas affichés pour le moment.

2024-01-25 21:59 UTC, ghorreso commented on src/components/articleInfo/BuyerProtectionInfo.tsx
> +    </div>
Corrigé

2024-01-25 22:03 UTC, ghorreso commented on src/components/articleInfo/ArticlePrices.tsx
> +  const [modalPriceDetails, setModalPriceDetails] = useState<boolean>(false);
Je préfère plutôt écrire comme ça alors: 

```tsx
const ArticlePrices = ({ price }: { price: number }) => {}
```

2024-01-25 22:07 UTC, ghorreso commented on __tests__/ArticleInfo.test.tsx
> +const testProduct: FakeProduct = {
Ok je l'ai mis dans un fichier `__tests__/data/testProduct.ts`

2024-01-25 22:08 UTC, ghorreso commented on src/components/ArticleInfo.tsx
> +};
C'est changé

2024-01-25 22:09 UTC, ghorreso commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +};
changé

2024-01-26 15:33 UTC, belewen commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
Si je prends par exemple la première ligne :
```
 <span>MARQUE</span>
      <span>TOMMY HILFIGER</span>
```
Je remplace par
    ```
  <tbody>
      <tr>
      <td>Marque</td>
<td>TOMMY HilFIGER</td>
```
etc...

Je pense que le code sera plus pertinent qu'une succession de span

2024-01-26 15:34 UTC, belewen commented on src/components/articleInfo/ArticleDetails.tsx
> +    <div className="grid grid-cols-2 text-vintedTextGrisFonce">
Ca marche laisse comme ceci et je verrais l'affichage de la page une fois que tout sera mergé

2024-01-26 15:40 UTC, nabilCodeur commented on src/components/ArticleInfo.tsx
> +        <span>{description}</span>
ok

2024-01-26 15:51 UTC, belewen commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +    <div className="flex flex-row justify-between my-4">
Je te propose ce code , plus besoin de flex. 
```
<div className=" my-4">
      <p>Envoi <span className="text-vintedTextGrisFonce">
        à partir de 500€</span>
        </p>
      
    </div>
```

2024-01-26 15:52 UTC, belewen commented on src/components/articleInfo/ArticleInfoButtons.tsx
> +    </div>
ok on verra lors du merge

2024-01-26 16:58 UTC, ghorreso commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +    <div className="flex flex-row justify-between my-4">
Non y a besoin du flex vu que "Envoi" et "à partir de" doivent être séparés à chaque extrémité.

Avec ton code ça donne : 

<img width="349" alt="image" src="https://github.com/arnaudpant/vinted/assets/10980068/f6f2ea71-41e7-430c-b7ff-8f6229168461">

Sur le site de Vinted, ça donne : 

<img width="328" alt="image" src="https://github.com/arnaudpant/vinted/assets/10980068/7eeacd4d-6374-44f5-a392-84ed503af2fe">

2024-01-26 17:05 UTC, ghorreso commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
Avec un tableau, ça ne s'affiche pas comme il faut : 

![image](https://github.com/arnaudpant/vinted/assets/10980068/37e15a21-4c18-4cf7-941e-23e99e5e55a1)

2024-01-26 18:29 UTC, belewen commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
> +    <div className="flex flex-row justify-between my-4">
ok, effectivement dans ce cas c'est mieux de garder le code original

2024-01-26 18:39 UTC, belewen commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
J'ai ajouté quelques propriétés tailwind à table, je trouve que cela rend bien. Si cela pose toujours problème, on garde le code d'origine pour ne pas perdre trop de temps là dessus
```
 <table className="border-separate border-spacing-x-4  ">
          <tbody>
            <tr>
              <td>Marque</td>
              <td>TOMMY HILFIGER</td>
            </tr>
            <tr className="">
              <td>TAILLE</td>
              <td>12 ans</td>
            </tr>
            <tr>
              <td>TAILLE</td>
              <td>15 ans</td>
            </tr>
            <tr className="">
              <td>LOCALISATION</td>
              <td>LE BOULLAY-LES-DEUX-ÉGLISES, FRANCE</td>
            </tr>
          </tbody>
        </table>
```

2024-01-26 21:54 UTC, ghorreso commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
Non, je maintiens, je préfère perso le grid qui gère aussi l'espacement en fonction de la taille de l'écran. Et aussi la succession de span peut te déranger actuellement car c'est codé en dur. Si j'ai les vraies données dynamiques, ce serait simplement un map avec 2 spans à afficher à chaque fois.

2024-01-26 22:25 UTC, ghorreso commented on src/components/articleInfo/BuyerProtectionInfo.tsx
> +        </svg>
C'est déjà le cas, c'est dans src/assets/buyer-protection-shield.svg, tu veux faire quoi de plus ?

2024-01-30 20:30 UTC, belewen commented on src/components/articleInfo/BuyerProtectionInfo.tsx
> +        </svg>
Je ne comprends pas ta réponse. Il existe  bien dans le fichier BuyerProtectionInfo.tsx une balise svg allant de la ligne 5 à 30.
Comme le code du svg est déjà dans buyer-protection-shield.svg , pourquoi ne pas l'importer et l'utiliser directement dans BuyerProtectionInfo.tsx.

Ce qui donnerait ligne 5:
`<img src = {buyerProtectionShield}  alt="buyer protection shield"/>`
Avec
` import {buyerProtectionShield} from "path/ buyer-protection-shield.svg"`

2024-01-30 20:31 UTC, belewen commented on src/components/articleInfo/ArticlePrices.tsx
> +  const [modalPriceDetails, setModalPriceDetails] = useState<boolean>(false);
ok

2024-01-30 20:33 UTC, belewen commented on src/components/articleInfo/ArticleDetails.tsx
> +      <span>{getTimeDifferenceString(creationAt)}</span>
ok on laisse comme ça

2024-01-30 20:51 UTC, ghorreso commented on src/components/articleInfo/BuyerProtectionInfo.tsx
> +        </svg>
Ok je ne connaissais pas la méthode en fait. C'est donc changé

2024-01-31 14:53 UTC, nabilCodeur approved these changes

2024-02-01 18:30 UTC, merged