Sprint 2 - Prise en compte des remarques de omid des problemes de la branche dev…
arnaudpant/vinted pull request #22
Opened 2024-01-30 19:37 UTC by belewen

ordre tailwind css
Suppression nvm.txt
FakeShopProvider dans main.tsx uniquement
Quelques suppressions d'import inutiles
Quelques autres modifications mineures

2024-01-30 20:58 UTC, ghorreso approved these changes
Ok pour merger dans develop

2024-01-30 21:00 UTC, ghorreso requested changes
A quoi sert prettier-plugin-tailwindcss ? J'ai l'impression qu'il ordonne les classes tailwind mais on le fait déjà vu qu'il y a plugin:tailwindcss/recommended non ?

2024-01-31 17:09 UTC, belewen commented
prettier plugin tailwindcss je l'ai installé car il semblait que je n'avais pas en évidence pas les recommendations de l'ordre css. 
Puis finalement cela s'est avéré inutile.
Je n'ai pas pensé à le désintaller avant de push. Je viens de le faire en local et je vais push de nouveau. 
Au passage je remarque que cette installation a  aussi mise à jour prettier dans une nouvelle version. Je te propose de conserver cette modification

2024-02-01 18:26 UTC, ghorreso approved these changes

2024-02-01 18:45 UTC, merged