Sprint 2  - Ajout d'un composant LoadingCircularProgress
arnaudpant/vinted pull request #23
Opened 2024-01-30 20:02 UTC by belewen

2024-01-30 21:03 UTC, ghorreso requested changes

2024-01-30 21:03 UTC, ghorreso commented on src/components/ui/Loading.tsx
Le nom du fichier et du composant ne sont pas les mêmes

2024-01-31 12:39 UTC, belewen commented on src/components/ui/Loading.tsx
ok corrigé

2024-02-01 18:16 UTC, ghorreso approved these changes

2024-02-01 18:18 UTC, merged