Corr home
arnaudpant/vinted pull request #24
Opened 2024-02-01 09:30 UTC by arnaudpant

SPRINT 4 Arnaud

Corrections page Home:
- Suppression appel API => Contexte
- Scroll horizontale des articles
- Modifications CSS pour visuel des articles plus proche de ceux de Vinted
- Fil d'actu avec avatar

Modal connexion:
- Spinner de chargement lors de l'appel a Firebase

2024-02-01 23:40 UTC, ghorreso requested changes
Review terminée, quelques modifs nécessaires

2024-02-01 23:40 UTC, ghorreso commented on .env.example
> +VITE_urlUsers='API_URL_USERS'
Il faudrait supprimer VITE_urlProducts et VITE_urlUsers vu qu'ils ne sont plus utilisés

2024-02-01 23:40 UTC, ghorreso commented on src/components/home/ProductCard.tsx
> +  const idDivToScrollProductCard = 'divToScrollProductCard';
quand je veux scroller sur "Articles populaires", c'est "Explorer les articles de créateur" qui bouge

Je pense que ça vient du fait que les 2 sont créés avec ProductCard qui donne les mêmes idDivParentProductCard et idDivToScrollProductCard pour les 2

2024-02-01 23:40 UTC, ghorreso commented on src/components/header/header-top/buttons-action/MenuUserConnected.tsx
> +            Se déconnecter
Quand je clique sur "Se déconnecter", le modal "Se connecter" apparait. Alors que ça devrait être la page d'accueil.

2024-02-01 23:40 UTC, ghorreso commented on src/components/modals/authentification/ModalAuthConnexionView.tsx
> +    setIsLoading(true)
Est-ce que ce setIsLoading(true) est nécessaire vu que handleSignInUser fait aussi un setIsLoading(true) ?

Surtout que c'est lui qui remet loading à false

2024-02-01 23:40 UTC, ghorreso commented on src/components/modals/authentification/ModalAuthConnexionView.tsx
> +    navigate('/')
Est-ce que setIsLoading(false) ne devrait pas plutôt être avant le if (error) ?
Sinon il n'est pas setté à false s'il n'y a pas d'erreur. Ce serait donc comme ça :

```tsx

  const handleSignInUser = async ({
    email,
    password,
  }: LoginFormTypeConnexion) => {
    setIsLoading(true);
    const { error } = await firebaseSignInUser(email, password);
    setIsLoading(false);
    if (error) {
      console.log('Error handleSignInUser');
      return;
    }
    reset();
    navigate('/')
  };


```

2024-02-01 23:40 UTC, ghorreso commented on src/components/modals/authentification/ModalAuthInscription.tsx
> +    setIsLoading(true);
Même commentaire que src/components/modals/authentification/ModalAuthConnexionView.tsx

2024-02-01 23:40 UTC, ghorreso commented on src/components/modals/authentification/ModalAuthInscription.tsx
>        console.log('Error ModalAuthInscription');
Je crois qu'il manque un setIsLoading(false) si on rentre dans cette condition

2024-02-01 23:40 UTC, ghorreso commented on src/components/modals/authentification/ModalAuthInscription.tsx
> +      setIsLoading(false);
Même commentaire que pour src/components/modals/authentification/ModalAuthConnexionView.tsx. Je mettrait setIsLoading(false); avant "if (error)"

2024-02-01 23:40 UTC, ghorreso commented on src/components/home/ProductCard.tsx
> +              <Skeleton className="h-[300px] w-[213px]" />
Pour ne pas dupliquer 5 fois le skeleton, on peut faire ça : 

```tsx

{Array(5)
    .fill('')
    .map((_, index) => (
        <Skeleton key={index} className="h-[300px] w-[213px]" />
    ))}
```

2024-02-01 23:40 UTC, ghorreso commented on src/components/home/ProductCardView.tsx
Où est utilisé src/components/home/ProductCardView.tsx ?

2024-02-01 23:40 UTC, ghorreso commented on src/components/home/NewsFeed.tsx
> +                        className="h-6 w-6 rounded-full"
Il manque un alt pour l'image

2024-02-01 23:40 UTC, ghorreso commented on src/components/home/NewsFeed.tsx
> +                      <img className="h-8 w-8 rounded-full" src="./avatar.png" />
Il manque un alt pour l'image

2024-02-01 23:40 UTC, ghorreso commented on src/components/home/NewsFeed.tsx
> +                  </div>
Cette partie est la même dans src/components/home/NewsFeed.tsx et src/components/home/ProductCard.tsx

Je pense que ça serait mieux de factoriser


```tsx
<img src={product.images[0]} alt={product.title} />
<div className="h-[90px] w-full p-2">
    <p className="text-sm">{product.price},00€</p>
    <p className="text-xs text-vintedGreen">
        {product.price},00€ incl
    </p>
    <p className="text-xs text-vintedTextGrisClair">Taille</p>
    <h2 className="text-xs text-vintedTextGrisClair">Marque</h2>
</div>
```

2024-02-01 23:54 UTC, ghorreso commented on src/components/header/header-top/buttons-action/MenuUserConnected.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:55 UTC, ghorreso commented on src/components/header/header-top/buttons-action/ButtonsUserConnected.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:55 UTC, ghorreso commented on src/components/header/header-top/TopHeader.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:56 UTC, ghorreso commented on src/components/ui/ChevronPosition.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:57 UTC, ghorreso commented on src/components/home/NewsFeed.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:58 UTC, ghorreso commented on src/utils/Utils.ts
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:59 UTC, ghorreso commented on src/types/types.ts
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:59 UTC, ghorreso commented on src/pages/Home.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:59 UTC, ghorreso commented on src/pages/Authentification.tsx
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-01 23:59 UTC, ghorreso commented on src/hooks/useDataFakeShop.ts
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-02 00:00 UTC, ghorreso commented on src/data/categoriesHeader.ts
prettier n'a pas l'air d'avoir traité ce fichier. J'ai du formatage qui est fait chez moi.

2024-02-02 08:48 UTC, arnaudpant commented on .env.example
> +VITE_urlUsers='API_URL_USERS'
Fait

2024-02-02 09:18 UTC, arnaudpant commented on src/components/home/ProductCard.tsx
> +  const idDivToScrollProductCard = 'divToScrollProductCard';
Probleme résolu

2024-02-02 09:37 UTC, arnaudpant commented on src/components/header/header-top/buttons-action/MenuUserConnected.tsx
> +            Se déconnecter
Problème résolu

2024-02-02 09:43 UTC, arnaudpant commented on src/components/modals/authentification/ModalAuthConnexionView.tsx
> +    setIsLoading(true)
En test quand j'ai développé cette fonctionnalité j'avais pas toujours le spinner qui se déclenchait. J'en ai supprimé un après plusieurs tests bon

2024-02-02 09:45 UTC, arnaudpant commented on src/components/modals/authentification/ModalAuthConnexionView.tsx
> +    navigate('/')
non il est là que en cas d'erreur pour supprimer le spinner.

2024-02-02 09:47 UTC, arnaudpant commented on src/components/modals/authentification/ModalAuthInscription.tsx
> +    setIsLoading(true);
meme reponse et correction

2024-02-02 09:49 UTC, arnaudpant commented on src/components/modals/authentification/ModalAuthInscription.tsx
>        console.log('Error ModalAuthInscription');
Corrigé

2024-02-02 09:49 UTC, arnaudpant commented on src/components/modals/authentification/ModalAuthInscription.tsx
> +      setIsLoading(false);
Meme réponse: Négatif

2024-02-02 09:52 UTC, arnaudpant commented on src/components/home/ProductCard.tsx
> +              <Skeleton className="h-[300px] w-[213px]" />
Ah cool, celle la je la note car je galère toujours avec ce type de rendu

2024-02-02 09:54 UTC, arnaudpant commented on src/components/home/ProductCardView.tsx
Nul part, c'etait une version que j'ai pas gardé
Supprimé

2024-02-02 09:55 UTC, arnaudpant commented on src/components/home/NewsFeed.tsx
> +                        className="h-6 w-6 rounded-full"
corrigé

2024-02-02 09:55 UTC, arnaudpant commented on src/components/home/NewsFeed.tsx
> +                      <img className="h-8 w-8 rounded-full" src="./avatar.png" />
corrigé

2024-02-02 10:04 UTC, arnaudpant commented on src/components/home/NewsFeed.tsx
> +                  </div>
Fait j'ai créé un nouveau composant

2024-02-02 10:07 UTC, arnaudpant commented on src/components/header/header-top/buttons-action/MenuUserConnected.tsx
Je suis sur File, j'ai pas l'option true

2024-02-02 10:09 UTC, arnaudpant commented on src/components/header/header-top/buttons-action/ButtonsUserConnected.tsx
Il faut que je sauvegarde manuellement, quand c'est VSCode qui sauvegarde il formate pas

2024-02-02 10:09 UTC, arnaudpant commented on src/components/header/header-top/TopHeader.tsx
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/components/ui/ChevronPosition.tsx
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/components/home/NewsFeed.tsx
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/utils/Utils.ts
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/types/types.ts
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/pages/Home.tsx
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/pages/Authentification.tsx
idem

2024-02-02 10:09 UTC, arnaudpant commented on src/hooks/useDataFakeShop.ts
idem

2024-02-02 10:10 UTC, arnaudpant commented on src/data/categoriesHeader.ts
idem

2024-02-02 13:21 UTC, ghorreso approved these changes
Ok pour merger

2024-02-02 16:51 UTC, ghorreso approved these changes
Ok pour merger

2024-02-02 21:27 UTC, merged