Feat/user profil
arnaudpant/vinted pull request #36
Opened 2024-02-03 19:44 UTC by belewen

Permet d'afficher l'utilisateur connecté avec le endpoint   /member

Comme il n'y a plus qu'un seul meùbre possible actuellement, le test user de firestore, j'ai enlevé tout ce qui concerne l'userId.
A savoir aussi que les images produits de la fake api sont inconsistantes, l'url change fréquemment et a un format étrange.  Exemple : "[\"https://api.escuelajs.co/api/v1/files/02cb.jpg\"]" . 
Il y'a deux semaines c'était autre chose. 
J'ai donc opté pour l'affichage de l'image de la catégorie du produit, qui elle n'a pas bougée.

2024-02-04 00:35 UTC, ghorreso requested changes
Review terminée

2024-02-04 00:35 UTC, ghorreso commented on src/App.tsx
> +          <Route path="/member/" element={<User />} />
Tu peux utiliser le userId même si on a un seul user. C'est authUser?.uid, authUser étant partagé par useFirebaseAuth

2024-02-04 00:35 UTC, ghorreso commented on src/pages/User.tsx
> +  if (!user) return <LoadingCircularProgress />;
ça reste en loading permanent si on est déconnecté.
Sur Discord, j'ai demandé à Arnaud de partager une variable "loading" via useFirebaseAuth

Sinon faut retourner ModalAuth quand il n'y a pas de user
```tsx
<ModalAuth setModalConnexion={() => {}} />
```

2024-02-04 00:35 UTC, ghorreso commented on src/types/types.ts
> +export type FakeUserWithStatistic = FakeUser & {
FakeUserWithStatistic n'est pas utilisé donc faut le supprimer

2024-02-04 00:35 UTC, ghorreso commented on src/pages/User.tsx
> +export const UserContext = createContext({});
Ton contexte est mal définie car il ne renvoie pas un UserInterface explicitement. ça devrait être comme ça: 

```tsx

export const UserContext = createContext<UserInterface>({
  uid: '',
  email: '',
  displayName: '',
  emailVerified: true,
  photoURL: '',
});
```

2024-02-04 00:35 UTC, ghorreso commented on src/components/ArticlesAvailables/models/PictureUser.tsx
>    avatarUser: string;
avatarUser peut aussi être undefined

2024-02-04 00:35 UTC, ghorreso commented on src/components/ArticlesAvailables/models/PictureUser.tsx
Pourquoi c'est dans src/components/ArticlesAvailables/models alors que c'est aussi utilisé par src/components/userProfil/UserSynopsis.tsx ?

2024-02-04 00:35 UTC, ghorreso commented on src/components/ArticlesAvailables/models/PictureUser.tsx
> +  if (!avatarUser) return <CircleUserRound size={pictureSize} color="green" />;
Ce n'est pas cohérent avec src/components/header/header-top/buttons-action/ButtonsUserConnected.tsx qui affiche avatar.png si l'avatar n'est pas défini. Faut que les 2 soient les mêmes

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/UserSynopsis.tsx
> +        <h1 className="font-semibold">{user.displayName ?? 'Vinted'}</h1>
Pourquoi "Vinted" si user.displayName n'est pas définie ?

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/UserInfosLine.tsx
> +        <UserInfoLine ComponentPicture={<MapPin />}>
Mauvais logo. C'est plutôt [rss](https://lucide.dev/icons/rss)

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/UserInfosLine.tsx
> +    <div className="grid w-full grid-cols-2 gap-x-32 gap-y-4 text-nowrap  text-vintedTextBlackVar">
Il faut mettre de l'espace avec l'évaluation: ça se corrige avec un mt-10 par exemple

<img width="664" alt="image" src="https://github.com/arnaudpant/vinted/assets/10980068/3995d03b-37d6-41bf-a741-07eda3babc2d">

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/dressingTab/ButtonContact.tsx
Pourquoi c'est dans src/components/userProfil/dressingTab ?

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/dressingTab/ButtonsContact.tsx
Pourquoi c'est dans src/components/userProfil/dressingTab ?

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/UserTabs.tsx
> +const UserTabs: React.FC = () => {
Les tabs ont la même logique et il y a des magic strings ("dressing", "about", etc). Il faut donc utiliser une liste dans ce cas comme ça:

```tsx
const UserTabs: React.FC = () => {
  const tabs = [
    {
      value: 'dressing',
      label: 'dressing',
      component: <UserDressingProfil />,
    },
    {
      value: 'evaluations',
      label: 'Evaluations',
      component: <UserEvaluation />,
    },
    {
      value: 'about',
      label: 'A propos',
      component: <UserAboutTab />,
      className: 'sm:hidden',
    },
  ];
  return (
    <div>
      <Tabs defaultValue={tabs[0].value}>
        <TabsList className="grid w-full grid-cols-3 sm:w-1/2 sm:grid-cols-2 ">
          {tabs.map((tab) => {
            return (
              <TabsTrigger
                key={tab.value}
                value={tab.value}
                className={tab.className}
              >
                {tab.label}
              </TabsTrigger>
            );
          })}
        </TabsList>
        {tabs.map((tab) => {
          return (
            <TabsContent
              key={tab.value}
              value={tab.value}
              className={tab.className}
            >
              {tab.component}
            </TabsContent>
          );
        })}
      </Tabs>
    </div>
  );
};
```

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/dressingTab/UserDressingProfil.tsx
> +        <UserDressingInfos />
Je crois que c'est plutôt UserInfos

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/dressingTab/UserReview.tsx
> +          {<span className="ml-2">200 avis</span>}
Les accolades servent à rien

2024-02-04 00:35 UTC, ghorreso commented on __tests__/CommentFromUser.tsx
Fichier vide, à supprimer

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/aboutTab/UserAboutInfos.tsx
> +import React from 'react';
Ligne en trop

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/UserInfosLine.tsx
Nom de fichier et du composant pas les mêmes

2024-02-04 00:35 UTC, ghorreso commented on src/pages/User.tsx
> +export const UserContext = createContext({});
Il faut définir le contexte dans le dossier context

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/UserInfosLine.tsx
> +          Bordeaux , France
Il faut utiliser user.userDocument?.city et user.userDocument?.country

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/aboutTab/UserAboutDetails.tsx
> +import React from 'react';
A supprimer

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/aboutTab/UserAboutDetails.tsx
> +        <p>Espagne</p>
Utiliser user.userDocument?.country

2024-02-04 00:35 UTC, ghorreso commented on src/components/userProfil/dressingTab/UserDressingInfos.tsx
> +        <p>Espagne</p>
Utiliser user.userDocument?.country

2024-02-04 00:35 UTC, ghorreso commented on src/components/header/header-top/buttons-action/MenuUserConnected.tsx
> +          <Link to="/member">Mon profil</Link>
Utiliser authUser?.uid

2024-02-04 00:35 UTC, ghorreso commented on src/components/ArticlesAvailables/models/UserBanner.tsx
> +  const { authUser }: { authUser: UserInterface | null } = useFirebaseAuth();
A quoi sert de mettre authUser: UserInterface | null vu que c'est ce qu'envoie useFirebaseAuth ?

2024-02-04 16:39 UTC, belewen commented on __tests__/CommentFromUser.tsx
ok

2024-02-04 16:42 UTC, belewen commented on src/App.tsx
> +          <Route path="/member/" element={<User />} />
Je pense que c'est mieux de laisser comme cela tant qu'on n'a pas quelques users qui impliquent l'utilisation de userId.

2024-02-04 16:49 UTC, belewen commented on src/components/ArticlesAvailables/models/PictureUser.tsx
ok j'ai migré dans le dossier components

2024-02-04 16:51 UTC, belewen commented on src/components/ArticlesAvailables/models/UserBanner.tsx
> +  const { authUser }: { authUser: UserInterface | null } = useFirebaseAuth();
testé et l'inférence de authUser est toujours ok. K'autocomplétion fonctionne toujours correctement. Corrigé

2024-02-04 22:00 UTC, ghorreso commented on src/App.tsx
> +          <Route path="/member/" element={<User />} />
Ok comme tu veux

2024-02-04 22:07 UTC, ghorreso commented on src/components/userProfil/UserInfosLine.tsx
> +    <div className="grid w-full grid-cols-2 gap-x-32 gap-y-4 text-nowrap  text-vintedTextBlackVar">
Tu as ajouté un mt-6 à "A propos" seulement donc "Informations vérifiées" est décalée:

<img width="669" alt="image" src="https://github.com/arnaudpant/vinted/assets/10980068/7958a011-c355-49fd-bac4-6ddc6bd4b600">

2024-02-04 22:10 UTC, ghorreso commented on src/components/userProfil/UserInfosLine.tsx
> +          Bordeaux , France
Il manque le user.userDocument?.country

2024-02-04 22:15 UTC, ghorreso commented on src/pages/User.tsx
>    const { authUser: user }: { authUser: UserInterface | null } =
authUser: UserInterface | null n'est pas nécessaire

2024-02-04 22:17 UTC, ghorreso commented on src/components/userProfil/dressingTab/UserDressingInfos.tsx
> +  const user: UserInterface = useContext(UserContext);
Pourquoi faire "user: UserInterface" alors que useContext(UserContext); renvoie déjà un UserInterface ?

2024-02-04 22:18 UTC, ghorreso requested changes
Des modifs encore nécessaires

2024-02-06 09:10 UTC, ghorreso approved these changes
Ok pour merger en résolvant les 2 derniers soucis : [ici][https://github.com/arnaudpant/vinted/pull/36#discussion_r1477142565) et [celui-là]()

2024-02-06 09:10 UTC, ghorreso commented on src/components/PictureUser.tsx
> +      <img src="./avatar.png" alt="profil" className="h-8 w-8 rounded-full" />
Mauvaise affichage quand c'est l'avatar par défaut:

![2024-02-06 10_02_50-Clone Vinted](https://github.com/arnaudpant/vinted/assets/10980068/0076c4eb-320a-4738-b417-3f2540240a28)

2024-02-06 18:54 UTC, merged