SPRINT 4 - Feat/items gallery
arnaudpant/vinted pull request #37
Opened 2024-02-04 12:17 UTC by arnaudpant

Page description d'un article depuis la page Accueil via la fakeapi
- Codage de la partie de Bapt
- Intégration et modifications CSS des composants déja codés
- Ajout d'un authIsLoading dans le hook useFirebaseAuth

2024-02-04 14:06 UTC, ghorreso requested changes
Review terminée

2024-02-04 14:06 UTC, ghorreso commented on src/components/page-infos-article/ArticlesGallery.tsx
> +          <img src={article.images[0]} />
Il manque un alt

2024-02-04 14:06 UTC, ghorreso commented on src/hooks/useFirebaseAuth.ts
> +        setAuthUserIsLoading(true)
Je crois qu'il manque un setAuthUserIsLoading(false) quand le chargement des données de l'utilisateur est fini

2024-02-04 14:06 UTC, ghorreso commented on src/pages/Article.tsx
> +  const { state }  = location;
state est null si on arrive directement sur la page /items/5 par exemple

2024-02-04 14:06 UTC, ghorreso commented on src/components/page-infos-article/ArticleInfo.tsx
> +        {/* <BuyerProtectionInfo /> */}
Pourquoi est-ce que tu as retiré BuyerProtectionInfo ?

2024-02-04 14:06 UTC, ghorreso commented on src/pages/Article.tsx
>    const { id } = useParams();
pourquoi tu n'utilises pas l'id dans l'URL ?

2024-02-04 14:11 UTC, ghorreso commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
>    const shippingFee = price * 0.09;
J'ai vu ça par hasard avec le produit Classic Black Hooded Sweatshirt. Il faudrait donc limiter shippingFee a 2 chiffres après la virgule comme ceci:

```tsx
const shippingFee = Math.round(price * 0.09 * 100) / 100;
```

![image](https://github.com/arnaudpant/vinted/assets/10980068/ef395d5a-3781-461c-aa0a-66087d0311cd)

2024-02-04 14:16 UTC, ghorreso commented on src/pages/Article.tsx
Cela serait pratique d'avoir l'effet qui fait remonter la page tout en haut quand on arrive sur un article. Comme quand on change de film/série dans le clone de Netflix. Cela se ferait donc comme ça:

```tsx

  useEffect(
    () =>
      window.scrollTo({
        top: 0,
        behavior: 'smooth',
      }),
    [state, id],
  );
```

2024-02-04 16:10 UTC, arnaudpant commented on src/pages/Article.tsx
Fait

2024-02-04 16:12 UTC, arnaudpant commented on src/components/page-infos-article/ArticlesGallery.tsx
> +          <img src={article.images[0]} />
Fait

2024-02-04 16:17 UTC, arnaudpant commented on src/hooks/useFirebaseAuth.ts
> +        setAuthUserIsLoading(true)
Ca fonctionne sans mais je l'ai ajouté

2024-02-04 16:17 UTC, arnaudpant commented on src/pages/Article.tsx
> +  const { state }  = location;
On n'en a parlé, fonctionnement normal pour le moment

2024-02-04 16:17 UTC, arnaudpant commented on src/components/page-infos-article/ArticleInfo.tsx
> +        {/* <BuyerProtectionInfo /> */}
Réactivé

2024-02-04 16:19 UTC, arnaudpant commented on src/pages/Article.tsx
>    const { id } = useParams();
parce que je passe toutes les infos user via les props et useLocation qui permet de passer des props via l'url, pas besoin de useParams

2024-02-04 16:21 UTC, arnaudpant commented on src/components/articleInfo/ArticleShippingFeeInfo.tsx
>    const shippingFee = price * 0.09;
fait

2024-02-04 21:58 UTC, ghorreso approved these changes
Ok pour merger en corrigeant le useEffect dans ArticlesGallery

2024-02-04 21:58 UTC, ghorreso commented on src/components/page-infos-article/ArticlesGallery.tsx
> +  }, []);
Le use effect ne se lance pas lorsqu'on passe d'un article à un article. Il faut que "article" soit en dépendance pour faire le scroll à chaque fois qu'article change.

Et pourquoi il n'y a pas "behavior: 'smooth'," ?

2024-02-05 11:28 UTC, arnaudpant commented
Ajout page infos article lorsque l'on clique sur un article de la page d'accueil

2024-02-05 11:28 UTC, merged