Feature/error boundary
arnaudpant/vinted pull request #50
Opened 2024-02-07 20:04 UTC by belewen

Mise en place de ErrorBoundary. Nécessite la librairie react-error-boundary. Penser à faire un nom install.
J'ai aussi améliorer l'affichage de Error404

Après test, le ErrorBoundary fonctionne si l'erreur se produit au chargement de la page.

Exemple qui fonctionne

```

const MyComponent = (= =>{
if (condition) throw new Error...

return <p>Composant peut-être problématique</p>

```

Ce code ne fonctionne pas pour le error boundary

`<button onClick = {throwError}>Déclencher une erreur<button/>`

2024-02-07 20:44 UTC, ghorreso requested changes
2 changements à faire selon moi

2024-02-07 20:44 UTC, ghorreso commented on src/pages/User.tsx
Est-ce que ce fichier est en trop dans cette branche ?

2024-02-07 20:44 UTC, ghorreso commented on src/pages/ErrorPage.tsx
> +const ErrorPage = () => {
Je crois qu'il faudrait donner la possibilité de revenir sur la page d'accueil en ajoutant un lien. Sinon l'utilisateur est coincé et doit retaper l'url dans son navigateur.

2024-02-07 20:47 UTC, belewen commented on src/pages/ErrorPage.tsx
> +const ErrorPage = () => {
J'avais essayé avec un Link initialement cela ne fonctionnait pas. Comme si react router dom ne fonctionnait pas à l'intérieur d'un errrorBoundary.
Je peux mettre un <a> à la place

2024-02-07 21:03 UTC, belewen commented on src/pages/ErrorPage.tsx
> +const ErrorPage = () => {
Testé avec un <a> cela fonctionne correctement

2024-02-07 21:05 UTC, belewen commented on src/pages/User.tsx
Je ne saisis pas bien, peux-tu développer pourquoi tu penses cela ?
J'ai vu qu'il existe des conflits pour ce fichier et un autre, qui seront à résoudre.

2024-02-08 20:31 UTC, belewen commented on src/pages/ErrorPage.tsx
> +const ErrorPage = () => {
J'ai pu faire fonctionner le link

2024-02-08 20:35 UTC, ghorreso approved these changes
Ok pour merger

2024-02-08 20:36 UTC, merged